steps:
  - label: 'Clone Duniverse'
    command:
      - opam pin add -ny jbuilder --dev
      - opam pin add -ny dune https://github.com/ocaml/dune.git
      - opam pin add -y duniverse https://github.com/avsm/duniverse.git
      - git clone git://github.com/ocaml/opam /home/opam/opam
      - cd /home/opam/opam
      - opam exec -- duniverse opam opam dune-release utop bun odoc opam-depext -vv
      - opam exec -- duniverse dune -vv
      - cat .duniverse*.sxp
    agents:
      docker: "true"
      arch: "amd64"
    plugins:
      docker#v1.1.1:
        image: "ocaml/opam2"
        always_pull: true
