steps:
  - label: 'Opam Repo Rev'
    command:
      - 'cd /src/scripts && buildkite-agent artifact upload opam-ci-install'
      - 'cd /root && obi-buildkite bulk --arch=$ARCH --opam-repo-rev=$OPAM_REPO_REV -vv'
      - 'cd /root/_results && buildkite-agent artifact upload "bulk-*/*"'
      - 'cat /root/_results/bulk.yml | buildkite-agent pipeline upload'
    agents:
      docker: "true"
      os: "linux"
      pusher: "true"
    plugins:
      docker#v1.1.1:
        image: "ocaml/opam2-staging:obi-buildkite"
        workdir: /src
        always_pull: true
        environment:
          - DISTRO=${DISTRO?}
          - OCAML_VERSION=${OCAML_VERSION?}
          - OPAM_REPO_REV=${OPAM_REPO_REV?}
          - ARCH=${ARCH?}
      docker-login#v1.0.0:
        username: avsm
