steps:
  - label: 'Build Index'
    command:
      - 'opam switch 4.06'
      - 'rsync -a /src/ /home/opam/src/ && sudo chown -R opam /home/opam/src'
      - 'sudo apt update && sudo apt install -y m4 pkg-config'
      - 'opam pin add -n --dev dockerfile-opam'
      - 'opam pin add -n --dev ocaml-version'
      - 'opam pin add -n --dev yaml'
      - 'opam install --deps-only /home/opam/src'
      - 'cd /home/opam/src && opam exec -- jbuilder build'
      - 'rm -rf opam-repository'
      - 'git clone git://github.com/ocaml/opam-repository'
      - 'rm -rf obi-logs'
      - 'git clone -b builds --depth=1 git://github.com/avsm/obi-logs'
      - 'cd /home/opam/src && opam exec -- jbuilder exec -- obi-buildkite index -i obi-logs -r opam-repository -vv > index.sxp'
      - 'buildkite-agent artifact upload index.sxp'
      - 'cd obi-logs && buildkite-agent artifact upload maintainers.sxp'
    agents:
      docker: "true"
    plugins:
      docker#v1.1.1:
        image: "ocaml/opam2-staging"
        workdir: /src
        always_pull: true
        environment:
          - OPAMYES=1
          - OPAMJOBS=12
  - wait
  - label: 'Push Index'
    command:
      - ssh-add -D && ssh-add ~/.ssh/id_rsa.bulk && ssh-add -l
      - git config --global user.email 'bactrian@ocaml.org' && git config --global user.name 'Bactrian the Build Bot'
      - rm -rf index
      - git clone git@github.com:avsm/obi-logs index --reference .
      - git -C index checkout --orphan index
      - git -C index reset
      - git -C index clean -dxf
      - buildkite-agent artifact download 'index.sxp' index
      - git -C index add .
      - git -C index commit -m 'BuildKite Update'
      - git -C index push origin index -f
      - rm -rf  index
    retry:
      automatic:
        limit: 3
    agents:
      githubpusher: "true"
  - label: 'Push Maintainer Cache'
    command:
      - ssh-add -D && ssh-add ~/.ssh/id_rsa.bulk && ssh-add -l
      - git config --global user.email 'bactrian@ocaml.org' && git config --global user.name 'Bactrian the Build Bot'
      - rm -rf obi-logs
      - git clone git@github.com:avsm/obi-logs -b builds
      - buildkite-agent artifact download 'maintainers.sxp' obi-logs
      - git -C obi-logs add maintainers.sxp
      - git -C obi-logs commit -m 'BuildKite Maintainer Update'
      - git -C obi-logs push origin builds
      - rm -rf obi-logs
    retry:
      automatic:
        limit: 3
    agents:
      githubpusher: "true"
