steps:
  - label: 'Build'
    command: 'ls -la && id && opam switch create .'
    plugins:
      docker#v1.1.1:
        image: "ocaml/opam2:debian-9-ocaml"
        workdir: /home/opam/src
        environment:
          - OPAMYES=1

