steps:
  - label: 'Build'
    command: 'rsync -a /src /home/opam/src && sudo chown -R opam /home/opam/src && opam switch create . ocaml-base-compiler.4.06.1'
    plugins:
      docker#v1.1.1:
        image: "ocaml/opam2:debian-9-ocaml"
        workdir: /src
        environment:
          - OPAMYES=1

