steps:
  - label: 'Build'
    command:
      - 'rsync -a /src/ /home/opam/src/ && sudo chown -R opam /home/opam/src'
      - 'apt update && apt install -y m4'
      - 'opam pin add -n --dev dockerfile-opam'
      - 'opam pin add -n --dev ocaml-version'
      - 'opam install --deps-only /home/opam/src'
    plugins:
      docker#v1.1.1:
        image: "ocaml/opam2-staging:debian-9-ocaml-4.06-linux-amd64"
        workdir: /src
        always_pull: true
        environment:
          - OPAMYES=1

