steps:
  - label: 'Build'
    agents:
      arch: amd64
    command:
      - 'rsync -a /src/ /home/opam/src/ && sudo chown -R opam /home/opam/src'
      - 'sudo apt update && sudo apt install -y m4 pkg-config'
      - 'opam pin add -n --dev dockerfile-opam'
      - 'opam pin add -n --dev ocaml-version'
      - 'opam install --deps-only /home/opam/src'
      - 'cd /home/opam/src && opam exec -- jbuilder build'
      - 'cd /home/opam/src && opam exec -- jbuilder exec -- obi-buildkite gen -vv'
      - 'cd /home/opam/src/_results && buildkite-agent artifact upload "phase1-*/*"'
      - 'cat /home/opam/src/_results/phase1.yml | buildkite-agent pipeline upload'
    plugins:
      docker#v1.1.1:
        image: "ocaml/opam2-staging:debian-9-ocaml-4.06-linux-amd64"
        workdir: /src
        always_pull: true
        environment:
          - OPAMYES=1
          - OPAMJOBS=8
  - wait
  - command: 'echo All done'
